version: '1'

services:

  sfbackend:
    container_name: backend
    build: .
    restart: always
    depends_on:
      - mongosf
    ports:
      - 3000:3000

  mongosf:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
